### ISSUE TITLE
Model Version in your benchmark 

### ISSUE THREAD

**Issue by yqtianust** [textflint/textflint#10]
Hi,

in your website https://www.textflint.io, there are several benchmarks and each of them includes many models. 

I am wondering to know, whether you cloud also publish the commit of the models on which your benchmark is used? It will help others for further research (for example, If I modify one of the models and reevaluate its robustness using TextFLint, I can know which version is my baseline).

Definitely, I will appreciate it if the script of the benchmark can also be published.

Thanks.

**Comment by BeyonderXX** [comment]
Hi，

Our experimental results are all based on the open source code of paper, without over-tuning the parameters. It is defficult to provide all models and environments that can be run directly, cuz different codes rely on different software and hardware environments. But it is easy to reproduce a single open source model, good luck!

We are willing to provide the script, please send email to xiao_wang20@fudan.edu.cn  :)
