### ISSUE TITLE
Format Samples for NER

### ISSUE THREAD

**Issue by agr505** [textflint/textflint#11]
Hi, 

I greatly enjoyed reading your work. I am trying to use the Transformations for the CoNLL 2003 NER problem setting. How do I format the data samples for NER? If possible, it would be very helpful to be able to see a NER transformation example.

Thank you,

Aaron Reich

**Comment by Ac-Zyx** [comment]
If you want to declare NERSample, you can do it as following steps.
```
data = {'x': ['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.'],
        'y': ['B-ORG', 'O', 'B-MISC', 'O', 'O', 'O', 'B-MISC', 'O', 'O']}
# or other format
data = {'x':'EU rejects German call to boycott British lamb .' 
             'y': ['B-ORG', 'O', 'B-MISC', 'O', 'O', 'O', 'B-MISC', 'O', 'O']}
ner_sample = NERSample(data)
```
