### ISSUE TITLE
Example on analytical report

### ISSUE THREAD

**Issue by ledw** [textflint/textflint#15]
Hi team,
Thanks for the great work! I'm very interested in the robustness analysis, and wonder if you can provide an example on how to run a model and get analyzed results? Thanks!

**Comment by BeyonderXX** [comment]
Hi,
We will launch many demos within a week to introduce the use of our components in detail, including robustness reporting function.

Stick around  ：）

**Comment by BeyonderXX** [comment]
We have updated the documentation on how to obtain robustness reports.

Please refer to _textflint/docs/source/user/_
