### ISSUE TITLE
pip install textflint提示microsoft visual c++ 14.0 or greater is required

### ISSUE THREAD

**Issue by imgoodman** [textflint/textflint#16]
pip安装出错。该如何解决。谢谢

**Comment by anaivebird** [comment]
You need visual studio build tools to build python wheels on windows. This is not caused by TextFlint. Some packages do not release built package, so you has install visual studio build tools so that python could build the package.

Please refer to https://wiki.python.org/moin/WindowsCompilers

**Comment by linuxLiuda** [comment]
Visual Studio安装过程中提示找不到软件了，是微软停止支持了吗，而且最新的pip21.3.1中pybluez也找不到了，还有什么好的关于蓝牙的python第三方库的推荐吗
