### ISSUE TITLE
404 when downloading data

### ISSUE THREAD

**Issue by LouChao98** [textflint/textflint#17]
This link is broken <https://www.textflint.com/static/Tasks/DP/PennTreebank-domain.zip> at the section "Task Specific Transformations" for task "Dependency Parsing".

**Comment by LouChao98** [comment]
Another data problem for task "Dependency Parsing".

The data in section "Combination of universal and task-specific" seems to be incomplete. Only "RemoveSubtree" is contained in the data, and no "AddSubtree" is found.

**Comment by JotionJoestar** [comment]
Thanks for your feedback, we upload a new data, you can download it now : )
