### ISSUE TITLE
About model

### ISSUE THREAD

**Issue by gnniaaa** [textflint/textflint#24]
I wonder where can I find the FlintModel. Can you help me? Thanks a lot!

**Comment by gnniaaa** [comment]
When I used Textcnn_model.py as you show in 6_FlintModel.ipynb, I got an error like this:
AttributeError: type object 'TextCNNTorch' has no attribute 'task'
It seems something wrong with the model(maybe because of the Class I import), could you help me? Thanks~

**Comment by BeyonderXX** [comment]
Could you paste your FlintModel definition and your usage code?

**Comment by gnniaaa** [comment]
> Could you paste your FlintModel definition and your usage code?

I tried two FlintModels,the first one is:

from abc import ABC
import numpy as np
import sys
sys.path.append("/Users/gnniaaa/Desktop/NLP/modell")
from metrics import accuracy_score as Accuracy
__all__ = ["FlintModel"]
TASK_METRICS = {
    'SA': [{"name": "accuracy", "fun": Accuracy}]
}
CLASSIFICATION_TASKS = ['ABSA', 'SA', 'SM', 'NLI', 'TC']
ALLOWED_ATTACK_TASKS = ['SA', 'SM', 'NLI', 'TC']

class FlintModel(ABC):

    def __init__(
        self,
        model,
        tokenizer,
        task='SA',
        batch_size=1
    ):     
        super(FlintModel, self).__init__()
        if task not in TASK_METRICS:
            raise ValueError(f'Not support task {task} !')
        self.task = task
        self.model = model
        self.tokenizer = tokenizer
        self.batch_size = batch_size

    def evaluate(self, data_samples, prefix=''):
        outputs = []
        labels = []
        i = 0
        while i < len(data_samples):
            batch_samples = data_samples[i: i + self.batch_size]
            batch_inputs, batch_labels = self.unzip_samples(batch_samples)
            labels += batch_labels
            predicts = self.__call__(*batch_inputs)
            if self.task in CLASSIFICATION_TASKS:
                predicts = np.argmax(predicts, axis=-1)
            outputs += predicts.tolist()
            i += self.batch_size
        metrics_rst = {}
        for Metric in TASK_METRICS[self.task]:
            metrics_rst[prefix + Metric["name"]] \
                = Metric["fun"](outputs, np.array(labels))
        return metrics_rst

    def get_grad(self, *inputs):
        if self.task not in ALLOWED_ATTACK_TASKS:
            raise RuntimeError(f"Not support task {self.task} current...")
        return self.get_model_grad(*inputs)
    def __call__(self, *inputs):
        raise NotImplementedError()
    def get_model_grad(self, *inputs):
        raise NotImplementedError()
    def unzip_samples(self, data_samples):
        raise NotImplementedError()

The second one is:

import sys
sys.path.append("/Users/gnniaaa/Desktop/NLP/modell")
import torch
from textflint.input_layer.model.flint_model.torch_model import TorchModel
from textflint.input_layer.model.test_model.textcnn_torch_model import TextCNNTorchModel
from textflint.input_layer.model.test_model.glove_embedding import GloveEmbedding
from textflint.input_layer.model.tokenizers.glove_tokenizer import GloveTokenizer

class TextCNNTorch(TorchModel):
    def __init__(self):
        glove_embedding = GloveEmbedding()
        word2id = glove_embedding.word2id
        super().__init__(
            model=TextCNNTorchModel(
                init_embedding=glove_embedding.embedding
            ),
            task='SA',
            tokenizer=GloveTokenizer(
                word_id_map=word2id,
                unk_token_id=glove_embedding.oovid,
                pad_token_id=glove_embedding.padid,
                max_length=30
            )
        )
        self.label2id = {"positive": 0, "negative": 1}

    def __call__(self, batch_texts):
        model_device = next(self.model.parameters()).device
        inputs_ids = [self.encode(batch_text) for batch_text in batch_texts]
        ids = torch.tensor(inputs_ids).to(model_device)
        return self.model(ids).detach().cpu().numpy()

    def encode(self, inputs):
        return self.tokenizer.encode(inputs)

    def unzip_samples(self, data_samples):
        x = []
        y = []
        for sample in data_samples:
            x.append(sample['x'])
            y.append(self.label2id[sample['y']])
        return [x], y

My config.json is:
{
	"task": "SA",
	"out_dir": "DATA/",
	"flint_model": "modell/flint_model.py",
	"trans_methods": [
		"Ocr", ["SwapSpecialEnt-Movie", "AddSum-Person"]
	],
	"trans_config": {
		"Ocr": {
			"trans_p": 0.3
		}
	}
}

I used command like this:
from textflint import Engine
data_path = 'IMDB.csv'
config = 'config.json'
engine = Engine()
engine.run(data_path, config)

I also changed adapter.py line 138 " model = load_module_from_file('model', model)" to fit my own model like "model = load_module_from_file('FlintModel', model)".But error always emerged:
Traceback (most recent call last):
  File "/Users/gnniaaa/Desktop/NLP/try.py", line 5, in <module>
    engine.run(data_path, config)
  File "/opt/anaconda3/envs/NLPP/lib/python3.8/site-packages/textflint/engine.py", line 42, in run
    dataset, config, model = self.load(data_input, config, task, model)
  File "/opt/anaconda3/envs/NLPP/lib/python3.8/site-packages/textflint/engine.py", line 69, in load
    model = auto_flintmodel(model=model, task=config.task)
  File "/opt/anaconda3/envs/NLPP/lib/python3.8/site-packages/textflint/adapter.py", line 140, in auto_flintmodel
    assert model.task == task, f"The task of your FlintModel is " \
AttributeError: type object 'FlintModel' has no attribute 'task'

**Comment by BeyonderXX** [comment]
It is recommended that you install the 0.0.4 version of TextFlint. Just generate adversarial samples which means move "flint_model" option from config file, and then verify your model offline.  

FlintModel is a more complicated function, and it is easy to make mistakes if you are not familiar with the usage. The FlintModel document corresponds to the API in v0.0.1, and we plan to update a version this week to fix some of the bugs. 

Thanks your attention and the support!
