### ISSUE TITLE
Does the current textflint support Chinese named entity recognition tasks? 

### ISSUE THREAD

**Issue by guanghuixu** [textflint/textflint#25]
I tried to run textflint to generate Chinese NER samples but failed. It seems that only English is supported. Are there any examples or tutorials for generating Chinese NER samples?

**Comment by BeyonderXX** [comment]
We have developed some _Transformations_ for Chinese NER, but have not merged yet. 
It won’t be long before TextFlint will support Chinese for most NLP tasks :)
