### ISSUE TITLE
What is the CSV samples for NER?

### ISSUE THREAD

**Issue by dongguanting** [textflint/textflint#26]
what is the CSV samples for NER？I want to use CSV format as my dataset's format，but I just find json sample like this：
"x": ['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.'], "y": ['B-ORG', 'O', 'B-MISC', 'O', 'O', 'O', 'B-MISC', 'O', 'O']}

I transfer the snips dataset as csv and train it, but it seems wrong,so how can I figure out it? Could you please offer CSV format samples?
![image](https://user-images.githubusercontent.com/60767110/131018100-638bf277-10fa-45f3-8363-7f1359436a3b.png)
![image](https://user-images.githubusercontent.com/60767110/131018301-410c338f-1827-4d3c-a6df-49d168659360.png)

**Comment by BeyonderXX** [comment]
你好！
感谢反馈！你的csv格式没有错，是TextFlint的CSV 加载BUG，这边会尽快修复。
如果着急的话，建议先用 json 进行数据变形操作。

tip: 你的 entity label 并非是常规的 location、person、organization, 有一些NER的领域变形会失败，比如 ‘SwapEnt’ 系列变形，因为这些变形依赖外部实体资源，目前只提供 location、person、organization 三种词表：）

**Comment by BeyonderXX** [comment]
已经发布了 0.0.5 版本，修复了这个BUG ：）

如果还有问题的话，下次可以把输入和错误贴上来，方便复现。
