### ISSUE TITLE
Chinese NER 问题

### ISSUE THREAD

**Issue by 447428054** [textflint/textflint#29]
@qzhangFDU @gpengzhi @Tribleave @jiacheng-ye @Tannidy 请问中文命名实体增强与英文命名实体存在哪些区别呢？

中文按词做，当插入标点在实体中间，预测标签是将实体拆为两部分还是加上标点的也算实体
同理，当替换的同音词，同义词，反义词词语在实体中间，预测不是实体还是预测为实体呢

若是替换交叉实体增强，替换的类别该如何确定呢

谢谢啦

**Comment by qzhangFDU** [comment]
中文是按照实体词进行替换的，跟英文很类似

要保证变换出来的句子是个正常的语句，语法正确，不会出现标点符号、反义词这些插入在实体中间的情况

简单例子：  原句：我去北京出差。  北京是地名    变换后：我去墨脱出差。  墨脱是要求识别出来的地名

交叉实体的意思是CrossCategory？  这种要根据上下文进行判断

比如： 复旦大学扩大2022级直博生招生比例。  这里复旦大学是机构名，如果在训练语料里面复旦大学都是机构名

我们会根据上下文构造复旦大学为地名的例子，比如：这个商场位于复旦大学北面。  这里复旦大学就应该是地名。  

主要目的是测试模型是否只是记住了复旦大学对应的类别，还是使用上下文进行判断。

**Comment by 447428054** [comment]
@qzhangFDU 感谢您的回答
那么如果是下列的基础变换增强，是否原先为实体的就处理为非实体呢

据了解#，目前，在外商投资企业获得的人民币贷款中，有近一半是中国+银行提供]的。
这里的中国+银行，中间插入了+号，那么中国银行这个机构是不是就不应该识别为实体，还是中国+银行作为一整个实体呢

迄今，呼伦贝尔盟十[个旗市已全部进入全[电话直拨网，并成为锺国最大的电话本地网。
这里中国同音词替换为锺国，这里是否也不该识别为实体了呢

**Comment by qzhangFDU** [comment]
中国+银行  这种我自己觉得变形，看你自己怎么理解，如果想测试OOV实体或者有OCR识别噪声的情况，可以把中国+银行 当做实体处理，从上下文看这里应该是个机构名。

锺国这里和上面情况类似，你也可以认为是地名，测试模型对于同音的处理

**Comment by qzhangFDU** [comment]
并成为XXX最大的电话本地网   根据这个上下文 不管XXX具体是什么字  应该都被识别为地名
