### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by haonan-li** [textflint/textflint#3]
Hi, 

I find I can't install this library using `pip install`(my pip version is 21.0.1), the error is:

> ERROR: Could not find a version that satisfies the requirement TextFlint
> ERROR: No matching distribution found for TextFlint

So I install it from source, 
but when I import it, some other error occur, could you help me with that?

> from TextFlint.engine import Engine

> 
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-3-3145e585ed25> in <module>
> ----> 1 from TextFlint.engine import Engine
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/__init__.py in <module>
>       5 from .input_layer.config import Config
>       6 # from .data_manager import DataManager
> ----> 7 from .generation_layer.generator import Generator
>       8 from .generation_layer.validator import Validator
>       9 # from .engine import TREEngine as TextFlint
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/generation_layer/generator/__init__.py in <module>
> ----> 1 from .generator import Generator
>       2 from .ut_generator import UTGenerator
>       3 from .absa_generator import ABSAGenerator
>       4 from .coref_generator import CorefGenerator
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/generation_layer/generator/generator.py in <module>
>      10 from itertools import product
>      11 
> ---> 12 from ...input_layer.dataset import Dataset
>      13 from ..validator import Validator
>      14 from ...common.utils.logger import logger
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/input_layer/dataset/__init__.py in <module>
> ----> 1 from .dataset import Dataset, sample_map
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/input_layer/dataset/dataset.py in <module>
>      21 
>      22 
> ---> 23 sample_map = get_sample_map()
>      24 
>      25 
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/input_layer/dataset/dataset.py in get_sample_map()
>      15 
>      16 def get_sample_map():
> ---> 17     return task_class_load(SAMPLE_PATH,
>      18                            [key.upper() for key in NLP_TASK_MAP.keys()],
>      19                            Sample,
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/common/utils/load.py in task_class_load(pkg_path, task_list, base_class, filter_str)
>      32     modules = module_loader(pkg_path, filter_str)
>      33     task_class_map = {}
> ---> 34     for module in modules:
>      35         task = module.__name__.split('.')[-1].split('_')[0]
>      36         task_class = None
> 
> ~/.conda/envs/textflint/lib/python3.8/site-packages/TextFlint-0.0.1-py3.8.egg/TextFlint/common/utils/load.py in module_loader(dir_path, filter_str)
>      25         assert('TextFlint' in module_name)
>      26         module_name = module_name[module_name.find('TextFlint'):]
> ---> 27         yield importlib.import_module(module_name)
>      28         # yield module.module_finder.find_loader(module.name)[0].load_module()
>      29 
> 
> ~/.conda/envs/textflint/lib/python3.8/importlib/__init__.py in import_module(name, package)
>     125                 break
>     126             level += 1
> --> 127     return _bootstrap._gcd_import(name[level:], package, level)
>     128 
>     129 
> 
> ModuleNotFoundError: No module named 'TextFlint-0'

**Comment by BeyonderXX** [comment]
Hi,
thanks for your feedback !

For more rigorous testing, TextFlint was not released on pypi until the evening of 4.6. 

It's recommend to use `pip` to install text flint.
`pip install textflint`
