### ISSUE TITLE
Tutorial Update (No module named 'textflint.input_layer')

### ISSUE THREAD

**Issue by cooelf** [textflint/textflint#30]
Hi, 

Thanks for the contribution of the awesome platform. It seems there is some mismatch between the latest textflint version and the tutorial. 

For example, in "https://github.com/textflint/textflint/blob/master/docs/user/tutorials/7_BERT%20for%20POS%20tagging.ipynb", 
I think "from textflint.input_layer" should be "from textflint.input" :)

**Comment by BeyonderXX** [comment]
Indeed, the new version modified the package name, but the lack of synchronization tutorials caused this error. Thank Zhuosheng for pointing out this problem. The maintenance team will fix this problem soon.

**Comment by cooelf** [comment]
Great! Thanks!
