### ISSUE TITLE
Unable to download detachable_word file

### ISSUE THREAD

**Issue by JackGao09** [textflint/textflint#31]
https://textflint.oss-cn-beijing.aliyuncs.com/download/CWS_DATA/detachable_word seems broken, which leads to CWS SwapVerb does not work properly. Could you help me check it? Thank you!

**Comment by JackGao09** [comment]
btw, it will be better to have some examples introducing what detachable words are : )

**Comment by Ac-Zyx** [comment]
That resource has been repaired. You can delete the cache and download it again

**Comment by JackGao09** [comment]
> That resource has been repaired. You can delete the cache and download it again

I have cleared the cache and redownloaded it. The transformation works now, ty!
