### ISSUE TITLE
NER Task Specific Transformed CoNLL 2003 and OntoNotes v5 Training Sets

### ISSUE THREAD

**Issue by agr505** [textflint/textflint#33]
Hi,

I would like to use the TextFlint task-specific transformed CoNLL 2003 and OntoNotes v5 Training Sets for experiments in my paper. Are these transformed training sets readily downloadable? On textflint.io I was only able to find the transformed test sets of these datasets.

Thank you for the help,

Aaron

**Comment by agr505** [comment]
Ok great, thank you. Please let me know after they've been uploaded.

Best Regards,

Aaron Reich

**Comment by BeyonderXX** [comment]
Sorry for not responding in time, 
The data has been uploaded to [textflint.io](textflint.io).

Xiao Wang

**Comment by BeyonderXX** [comment]
We just provide transformed **Test Sets** on our website for robust evaluation.
If you need data augmentation, you can transform the original training set with our toolkit.

Follow[ the NER tutorial](https://github.com/textflint/textflint/blob/master/docs/user/tutorials/11_NER.ipynb).

Best Regards,

Xiao Wang

**Comment by agr505** [comment]
So the transformed training sets will not be uploaded to the site then? 

I can follow the tutorial but I was wondering if you could provide CoNLL2003 in JSON or CSV format to allow it to be used in the tutorial notebook? Or is there a utility I could be pointed to that converts the original CoNLL training set to JSON or CSV format?

Thank you,

Aaron Reich
