### ISSUE TITLE
CrossCategory, OOV, SwapLonger not working for NER Task

### ISSUE THREAD

**Issue by agr505** [textflint/textflint#34]
Hi,

I was able to use TextFlint to augment the CoNLL2003 training data with the EntTypos and the ConcatSent transformations for the NER task. Thank you very much for providing this. It is presenting an error however when trying to use the other task-specific transformations: CrossCategory, OOV, SwapLonger on the NER Task showing this for each of those transformations: 

ValueError: Method CrossCategory is not allowed in task NER

Are these transformations supported? 

Best Regards,

Aaron

**Comment by BeyonderXX** [comment]
Hi,

Thanks for your feedback!
Could you provide your TextFlint version and your input examples?

Best Regards,

Aaron

**Comment by agr505** [comment]
Hi, 

The textflint version is the one downloaded in the tutorial: textflint-0.0.5

I attached the input examples I am using, it is the CoNLL 2003 training set.

Thank you,

Aaron
[conll2003 json.zip](https://github.com/textflint/textflint/files/7486727/conll2003.json.zip)
 .

**Comment by EnhydraGod** [comment]
> Hi,
> 
> The textflint version is the one downloaded in the tutorial: textflint-0.0.5
> 
> I attached the input examples I am using, it is the CoNLL 2003 training set.
> 
> Thank you,
> 
> Aaron [conll2003 json.zip](https://github.com/textflint/textflint/files/7486727/conll2003.json.zip) .

Hi there!  @agr505 :

Because CrossCategory, OOV, and SwapLonger all belong to the **swap entity**, so we have unified interfaces in the latest version of textflint. You can write the config.json by this:

```    
"trans_methods": [
      "SwapEnt"
]
```

And specify a specific transformation method in trans_config like this:

```
"trans_config" :{ 
        "SwapEnt": [
            {"swap_type": "CrossCategory"},
            {"swap_type": "OOV"},
            {"swap_type": "SwapLonger"}
        ]
}
```

For your task, just change **config.json** to this : [config.zip](https://github.com/textflint/textflint/files/7661183/config.zip)

```
{
    "task": "NER",
    "out_dir": "./DATA/",
    "trans_methods": [
      "SwapEnt"
    ],
    "trans_config" :{
        "SwapEnt": [
            {"swap_type": "CrossCategory"},
            {"swap_type": "OOV"},
            {"swap_type": "SwapLonger"}
        ]
    }
}
  
```

All the best,

EnhydraGod
