### ISSUE TITLE
输入格式问题

### ISSUE THREAD

**Issue by WeiModerate** [textflint/textflint#36]
data = [{'x': 'Jotion lives in Xian 105 kilometers away .',
       'y': ['B-PER', 'O', 'O', 'B-LOC', 'O', 'O', 'O', 'O']}]
数据是textflint/docs/user/tutorials/11_NER.ipynb中的示例
-------------------------------------------------------
engine = Engine()
engine.run(data_input=data,task='NER')
可以运行，即使用默认的config。
-------------------------------------------------------
config = Config()
config.task = 'NER'
config.out_dir = 'data/trans_data/'
config.trans_methods = ['EntTypos','SwapNamedEnt','Keyboard','Ocr','SpellingError','Tense','Typos','SwapAntWordNet','SwapSynWordNet']
engine = Engine()
engine.run(data_input=data,config=config)
而对config进行定制，则无法运行，报错如下
ValueError: Cant find attribute x from NERSample
-------------------------------------------------------
请问问题出在哪里呢？以及TextFlint有中文的文档吗？

**Comment by BeyonderXX** [comment]
你好，

感谢反馈！这个 Issue, @EnhydraGod 协助定位下。
另外TextFlint  近期会更新中文语料变形功能，届时会提供中文使用文档，尽情期待！

王枭

**Comment by EnhydraGod** [comment]
也许你应该尝试将config写入文件然后导入：

from textflint import Engine

data_path = 'input.json'
config = 'config.json'
engine = Engine()
engine.run(data_path, config)

@WeiModerate 

Ablustr
