### ISSUE TITLE
config

### ISSUE THREAD

**Issue by ilovedoudou** [textflint/textflint#4]
What is the format of the config file？ 
As the example，“engine.run(data_samples, out_dir_path, config)”， how to configure it to run？

**Comment by BeyonderXX** [comment]
Hi！
Config is not a necessary input to Engine, you can use default config to generate new samples.

Of course, you can also customize your own `config` file. The documentation for `config` is being prepared and will be updated to github soon. 

Recommend you to join our Wechat group by scan QR code, where you can ask your questions.
![WechatIMG420](https://user-images.githubusercontent.com/42961051/113820576-77348880-97ad-11eb-9d96-3faf8e913fa7.jpeg)
