### ISSUE TITLE
Error about installing textflint with setup.py

### ISSUE THREAD

**Issue by JackGao09** [textflint/textflint#41]
I installed textflint in my project by setup.py. However, an error occurred when I try to import the package, below is the screenshot:

![无标题](https://user-images.githubusercontent.com/85552544/147811043-9bc86377-b8c7-4a63-9024-bd45962428c9.png)

I have checked the variable `module_name` in `importlib.import_module(module_name)`, 
which is textflint-0.0.3-py3.8.egg.textflint.input_layer.component.sample.absa_sample

Any suggestions to solve this issue?

**Comment by BeyonderXX** [comment]
Hi,

We have not tested _setup.py_ too much.
Plz install with _pip_, which could download 0.0.4 version.

WangXiao

**Comment by JackGao09** [comment]
> Hi,
> 
> We have not tested _setup.py_ too much. Plz install with _pip_, which could download 0.0.5 version.
> 
> WangXiao

I see. Thanks for your suggestion!
