### ISSUE TITLE
Is anyone still maintaining this project?

### ISSUE THREAD

**Issue by EdwardMao** [textflint/textflint#47]
There are so many typo in code misleading users. 
For example:
In 4_Sample_Dataset.ipynb, the first line is "from TextFlint.input_layer.component.sample.sa_sample import SASample", which should be "from textflint.input.component.sample.sa_sample import SASample".
Try to be a user-friendly project, at least for the tutorial material.

**Comment by BeyonderXX** [comment]
Hi,
Thanks for pointing out the problem, we will fix this tutorial within 48 hours. 
The issue is caused by the version update, but the tutorial is not synchronized.

Xiao Wang

**Comment by BeyonderXX** [comment]
Hi,

The tutorial has been updated, but some new features will not work properly until the next version.

Xiao Wang
