### ISSUE TITLE
textflint是否支持Chinese Semantic Matching任务

### ISSUE THREAD

**Issue by guanghuixu** [textflint/textflint#51]
首先非常感谢textflint这个开源项目跟作者们~
我在主页上看到[demo](https://www.textflint.io/builder?task=SMCN)，textflint应该是已支持Chinese Semantic Matching任务的。
但我尝试使用时遇到了些困难，可能是我对textflint框架还不够熟悉。
我仿照[Chinese Word Segmentation任务](https://github.com/textflint/textflint/blob/master/docs/user/tutorials/10_CWS.ipynb)写了下测试代码，但并没有获得相应的鲁棒性增广数据。以下是我的代码
```
from textflint.engine import Engine
from textflint.adapter import auto_config
from textflint.input.config import Config
import os
engine = Engine()
# 是否只支持英文SM，还是中英文都共用SM，不像CWS特指chinese word segmentation
config = auto_config(task='SM')
config.trans_methods = [
    "SwapWord",
    ]
config.sub_methods = []
engine.run(os.path.normcase('test.json'), config=config)
```
测试数据`test.json`是参照主页中的[示例](https://www.textflint.io/builder?task=SMCN)
```{ "sentence1": "我喜欢这本书。", "sentence2": "这本书是我喜欢的。", "y": "1" }```
希望能尽快得到回复，谢谢~

**Comment by guanghuixu** [comment]
我好像定位到问题了，可能是这里的代码写错了
https://github.com/textflint/textflint/blob/master/textflint/common/settings.py#L315
重复定义了两次`SM`，但没有定义`SMCN`，修改后应该可以运行了
以下是新的测试代码：
```
from textflint.engine import Engine
from textflint.adapter import auto_config
from textflint.input.config import Config
import os

engine = Engine()
config = auto_config(config="Tasks/SMCN.json")
config.trans_methods = config.available_domain + config.available_ut
config.out_dir = 'output'
engine.run(os.path.normcase('output/test.json'), config=config)
```
`SMCN.json`如下：
```
{
        "task": "SMCN",
        "name": "SMCN",
        "full_name": "Chinese Semantic Matching",
        "description": "This task need model to identify whether two sentences express the same meaning.",
        "available_domain": [
                "SwapWord",
                "SwapNum",
                "Overlap"
        ],
        "available_ut": [
                "AppendIrr",
    		"BackTrans",
   		"CnSwapSynWordEmbedding",
    		"InsertAdv",
    		"CnSwapNum",
    		"CnSwapNamedEnt",
   		"CnSpellingError",
    		"CnPunctuation",
    		"CnPrejudice",
    		"CnDigit2Char",
    		"CnHomophones",
    		"CnSynonym"
        ]
}
```
此外，有另一个问题想问：textflint是否考虑中英混合的Chinese Semantic Matching任务？上述代码虽然可用，但如果想搭配英文的[攻击方法](https://github.com/textflint/textflint/blob/master/textflint/common/settings.py#L127)还是会报错，其实大可不必限制？

**Comment by guanghuixu** [comment]
有些攻击方法(如`CnSwapNum`)生成数据时是不是没有修改对应标签
ori: `{ "sentence1": "桌子上有3本书。", "sentence2": "有3本书在桌子上。", "y": "1" }`
trans: `{"sentence1": "桌子上有0本书。", "sentence2": "有1本书在桌子上。", "y": "1", "sample_id": 0}`

生成后的"y"明显不对

**Comment by BeyonderXX** [comment]
感谢你的建议！
这确实是个BUG， 我们会在24小时内修复！

中文的变形文档还在编写中，如果使用有问题，建议先参考下 Read the doc 里的API说明。
https://textflint.readthedocs.io/en/latest/

**Comment by BeyonderXX** [comment]
BUG已修复 ：）
