### ISSUE TITLE
Click dependency

### ISSUE THREAD

**Issue by helpmefindaname** [textflint/textflint#52]
Hello,

I am wondering why textflint has a pinned dependency on click (`click==7.1.1` in the `requirements.txt`), as from my understanding click is not even used in the project, [the cli script](https://github.com/textflint/textflint/blob/master/textflint/textflint_cli.py) seems to use argparse instead.
Would it be possible to get rid of that dependency?

**Comment by BeyonderXX** [comment]
Thanks for your feedback, it is possible to remove it from requirements.

In fact, `click` is a package that `textattack` depends on, which is used for adversarial attack feature. 
The specific information can be found here. 
https://github.com/QData/TextAttack/blob/master/requirements.txt

You can ignore it if you are just interested in transformation and subpopulation.

**Comment by helpmefindaname** [comment]
Thank you for the quick reply,
my problem was not having to install click at all, but the overly specific version pin. I have a dependency that requries `click>=8.0.0`
`TextAttack` allows `click<8.1.0` so that one is no problem, however I cannot add `textflint` to my requirements due to that pin.

I am currently solving this issue, by creating my own fork, which is a copy of this repo but removes that requirement, however I would prefer to directly use TextFlint instead, so I don't have to deal with the burdon of additional maintenance
