### ISSUE TITLE
support black-box attack and defense?

### ISSUE THREAD

**Issue by lihuiknight** [textflint/textflint#9]
Dear author, just a quick question. Does your toolkit support black-box adversarial training on text?

**Comment by anaivebird** [comment]
TextFlint is a robustness **testing** toolkit, only accuracy and F1 before and after attack will be outputed. Adversarial training to stength model is not supported by now.

**Comment by BeyonderXX** [comment]
Hi,

TextFlint does not support training. Because of the decoupling of the model and robustness verification, in order to support models implemented with any meachine learning framework.

 For defense, users can utilize TextFlint for adversarial training.

**Comment by lihuiknight** [comment]
Thanks for your reply. There are two more questions:

(1) How efficient does the attacker on the large-scale datasets?

(2) Does TextFlint support both categorical and numerical variables? Specifically, in my scenario, the input contains text, numerical features and categorical features. Any efficient approach to handle such richly set of data structures in the general framework?

**Comment by anaivebird** [comment]
(1) Most transformations are fast(string based), neural-net based transformations like masked languange model prediction replacement(MLM), backtranslation or transformations used NER are restricted by performance of nerual net inference or spacy NER parser speed.

We have do a lot of efforts to optimize MLM and NER-based transformation speed. For Quora Question Pairs dataset(consist of 40000 sentence pairs = 80000 sentences), backtranslation could finish in less than 10 hours. MLM and ner-based transformation like entity replacement could finish in less than 1 hour.

(2) See on https://www.textflint.io/, we do attack on datasets of 12 NLP tasks. As for as I know, we only support text feature attack.

**Comment by lihuiknight** [comment]
ok, thanks.  It looks pretty good. I am from Ant Group (Alibaba Group). And we are now hiring some smart interns on adversarial machine learning. If you are interested in  our job, welcome contact with me.

**Comment by anaivebird** [comment]
@lihuiknight Thanks. Could you leave a way to connect you?

**Comment by lihuiknight** [comment]
@anaivebird  keep in contact with my email:  lihuiknight@gmail.com
